package somossuinos.jackketch.transform;

class ActivityDiagramXml {

    private static final String XML =
            new String("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\" ?>                               ")
                    .concat("<ActivityDiagramGraph id=\"1\">                                                             ")
                    .concat("    <nodes id=\"2\">                                                                        ")
                    .concat("        <ScenarioStartNode id=\"3\">                                                        ")
                    .concat("            <children id=\"4\"/>                                                            ")
                    .concat("            <location class=\"Point2D.Double\" id=\"5\" x=\"780.0\" y=\"140.0\"/>           ")
                    .concat("            <id id=\"6\" value=\"727995c5-a419-4b19-a035-d68f3073be74\"/>                   ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor id=\"7\">                                                      ")
                    .concat("                <red>255</red>                                                              ")
                    .concat("                <green>255</green>                                                          ")
                    .concat("                <blue>255</blue>                                                            ")
                    .concat("                <alpha>255</alpha>                                                          ")
                    .concat("            </backgroundColor>                                                              ")
                    .concat("            <borderColor id=\"8\">                                                          ")
                    .concat("                <red>0</red>                                                                ")
                    .concat("                <green>0</green>                                                            ")
                    .concat("                <blue>0</blue>                                                              ")
                    .concat("                <alpha>255</alpha>                                                          ")
                    .concat("            </borderColor>                                                                  ")
                    .concat("            <textColor reference=\"8\"/>                                                    ")
                    .concat("        </ScenarioStartNode>                                                                ")
                    .concat("        <SynchronizationBarNode id=\"9\">                                                   ")
                    .concat("            <children id=\"10\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"11\" x=\"648.0\" y=\"210.0\"/>          ")
                    .concat("            <id id=\"12\" value=\"eda0107e-1f45-45a0-b0f9-578a9a624260\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"7\"/>                                              ")
                    .concat("            <borderColor reference=\"8\"/>                                                  ")
                    .concat("            <textColor reference=\"8\"/>                                                    ")
                    .concat("        </SynchronizationBarNode>                                                           ")
                    .concat("        <ActivityNode id=\"13\">                                                            ")
                    .concat("            <children id=\"14\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"15\" x=\"660.0\" y=\"270.0\"/>          ")
                    .concat("            <id id=\"16\" value=\"6f6aabb4-b073-4290-b303-5f9f0cd25fa7\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"7\"/>                                              ")
                    .concat("            <borderColor reference=\"8\"/>                                                  ")
                    .concat("            <textColor reference=\"8\"/>                                                    ")
                    .concat("            <name id=\"17\" justification=\"1\" size=\"4\" underlined=\"false\">            ")
                    .concat("                <text>x = 1 + 1</text>                                                      ")
                    .concat("            </name>                                                                         ")
                    .concat("        </ActivityNode>                                                                     ")
                    .concat("        <ActivityNode id=\"18\">                                                            ")
                    .concat("            <children id=\"19\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"20\" x=\"840.0\" y=\"270.0\"/>          ")
                    .concat("            <id id=\"21\" value=\"f768f0b0-beee-413c-b998-258e8ae81cc7\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"7\"/>                                              ")
                    .concat("            <borderColor reference=\"8\"/>                                                  ")
                    .concat("            <textColor reference=\"8\"/>                                                    ")
                    .concat("            <name id=\"22\" justification=\"1\" size=\"4\" underlined=\"false\">            ")
                    .concat("                <text>y = 1 * 1</text>                                                      ")
                    .concat("            </name>                                                                         ")
                    .concat("        </ActivityNode>                                                                     ")
                    .concat("        <SynchronizationBarNode id=\"23\">                                                  ")
                    .concat("            <children id=\"24\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"25\" x=\"648.0\" y=\"390.0\"/>          ")
                    .concat("            <id id=\"26\" value=\"935482ce-a20d-45fa-ba5d-c9cdfa6a348e\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"7\"/>                                              ")
                    .concat("            <borderColor reference=\"8\"/>                                                  ")
                    .concat("            <textColor reference=\"8\"/>                                                    ")
                    .concat("        </SynchronizationBarNode>                                                           ")
                    .concat("        <ActivityNode id=\"27\">                                                            ")
                    .concat("            <children id=\"28\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"29\" x=\"750.0\" y=\"460.0\"/>          ")
                    .concat("            <id id=\"30\" value=\"fc05a717-8385-4e54-bfd1-30e4f030eb10\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"7\"/>                                              ")
                    .concat("            <borderColor reference=\"8\"/>                                                  ")
                    .concat("            <textColor reference=\"8\"/>                                                    ")
                    .concat("            <name id=\"31\" justification=\"1\" size=\"4\" underlined=\"false\">            ")
                    .concat("                <text>v = x + y</text>                                                      ")
                    .concat("            </name>                                                                         ")
                    .concat("        </ActivityNode>                                                                     ")
                    .concat("        <DecisionNode id=\"32\">                                                            ")
                    .concat("            <children id=\"33\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"34\" x=\"750.0\" y=\"590.0\"/>          ")
                    .concat("            <id id=\"35\" value=\"f69f1f43-5e22-4036-8b9d-72c1b9ceb391\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"7\"/>                                              ")
                    .concat("            <borderColor reference=\"8\"/>                                                  ")
                    .concat("            <textColor reference=\"8\"/>                                                    ")
                    .concat("            <condition id=\"36\" justification=\"1\" size=\"4\" underlined=\"false\">       ")
                    .concat("                <text></text>                                                               ")
                    .concat("            </condition>                                                                    ")
                    .concat("        </DecisionNode>                                                                     ")
                    .concat("        <ActivityNode id=\"37\">                                                            ")
                    .concat("            <children id=\"38\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"39\" x=\"660.0\" y=\"690.0\"/>          ")
                    .concat("            <id id=\"40\" value=\"858e6795-aa8f-48f3-b90a-3131a91959de\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"7\"/>                                              ")
                    .concat("            <borderColor reference=\"8\"/>                                                  ")
                    .concat("            <textColor reference=\"8\"/>                                                    ")
                    .concat("            <name id=\"41\" justification=\"1\" size=\"4\" underlined=\"false\">            ")
                    .concat("                <text>Ok</text>                                                             ")
                    .concat("            </name>                                                                         ")
                    .concat("        </ActivityNode>                                                                     ")
                    .concat("        <ActivityNode id=\"42\">                                                            ")
                    .concat("            <children id=\"43\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"44\" x=\"840.0\" y=\"690.0\"/>          ")
                    .concat("            <id id=\"45\" value=\"a73b7d7d-d825-451c-86a2-8fdbc44d7d3e\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"7\"/>                                              ")
                    .concat("            <borderColor reference=\"8\"/>                                                  ")
                    .concat("            <textColor reference=\"8\"/>                                                    ")
                    .concat("            <name id=\"46\" justification=\"1\" size=\"4\" underlined=\"false\">            ")
                    .concat("                <text>Not Ok</text>                                                         ")
                    .concat("            </name>                                                                         ")
                    .concat("        </ActivityNode>                                                                     ")
                    .concat("        <ScenarioEndNode id=\"47\">                                                         ")
                    .concat("            <children id=\"48\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"49\" x=\"780.0\" y=\"910.0\"/>          ")
                    .concat("            <id id=\"50\" value=\"3e50ddfa-ea7a-4a0e-be65-7455702bed49\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"7\"/>                                              ")
                    .concat("            <borderColor reference=\"8\"/>                                                  ")
                    .concat("            <textColor reference=\"8\"/>                                                    ")
                    .concat("        </ScenarioEndNode>                                                                  ")
                    .concat("        <NoteNode id=\"51\">                                                                ")
                    .concat("            <children id=\"52\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"53\" x=\"950.0\" y=\"240.0\"/>          ")
                    .concat("            <id id=\"54\" value=\"c62d3638-1eec-410f-965c-97de8f9424b2\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor id=\"55\">                                                     ")
                    .concat("                <red>255</red>                                                              ")
                    .concat("                <green>255</green>                                                          ")
                    .concat("                <blue>255</blue>                                                            ")
                    .concat("                <alpha>255</alpha>                                                          ")
                    .concat("            </backgroundColor>                                                              ")
                    .concat("            <borderColor id=\"56\">                                                         ")
                    .concat("                <red>0</red>                                                                ")
                    .concat("                <green>0</green>                                                            ")
                    .concat("                <blue>0</blue>                                                              ")
                    .concat("                <alpha>255</alpha>                                                          ")
                    .concat("            </borderColor>                                                                  ")
                    .concat("            <textColor reference=\"56\"/>                                                   ")
                    .concat("            <text id=\"57\" justification=\"0\" size=\"4\" underlined=\"false\">            ")
                    .concat("                <text>{                                                                     ")
                    .concat("                    &quot;comment&quot;: &quot;Will sum multiply 1 * 1&quot;,               ")
                    .concat("                    &quot;package&quot;: &quot;somossuinos.jackketch.transform.violet&quot;,")
                    .concat("                    &quot;class&quot;: &quot;SimpleDiagram&quot;,                           ")
                    .concat("                    &quot;method&quot;: &quot;multiplyOneByOne&quot;                        ")
                    .concat("                    }</text>                                                                ")
                    .concat("            </text>                                                                         ")
                    .concat("            <color id=\"58\">                                                               ")
                    .concat("                <red>255</red>                                                              ")
                    .concat("                <green>228</green>                                                          ")
                    .concat("                <blue>181</blue>                                                            ")
                    .concat("                <alpha>255</alpha>                                                          ")
                    .concat("            </color>                                                                        ")
                    .concat("        </NoteNode>                                                                         ")
                    .concat("        <NoteNode id=\"59\">                                                                ")
                    .concat("            <children id=\"60\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"61\" x=\"270.0\" y=\"240.0\"/>          ")
                    .concat("            <id id=\"62\" value=\"be30b589-d550-492b-b362-07d937f7dab7\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"55\"/>                                             ")
                    .concat("            <borderColor reference=\"56\"/>                                                 ")
                    .concat("            <textColor reference=\"56\"/>                                                   ")
                    .concat("            <text id=\"63\" justification=\"0\" size=\"4\" underlined=\"false\">            ")
                    .concat("                <text>{                                                                     ")
                    .concat("                    &quot;comment&quot;: &quot;Will sum 1 + 1&quot;,                        ")
                    .concat("                    &quot;package&quot;: &quot;somossuinos.jackketch.transform.violet&quot;,")
                    .concat("                    &quot;class&quot;: &quot;SimpleDiagram&quot;,                           ")
                    .concat("                    &quot;method&quot;: &quot;sumOnePlusOne&quot;                           ")
                    .concat("                    }</text>                                                                ")
                    .concat("            </text>                                                                         ")
                    .concat("            <color id=\"64\">                                                               ")
                    .concat("                <red>255</red>                                                              ")
                    .concat("                <green>239</green>                                                          ")
                    .concat("                <blue>213</blue>                                                            ")
                    .concat("                <alpha>255</alpha>                                                          ")
                    .concat("            </color>                                                                        ")
                    .concat("        </NoteNode>                                                                         ")
                    .concat("        <NoteNode id=\"65\">                                                                ")
                    .concat("            <children id=\"66\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"67\" x=\"950.0\" y=\"430.0\"/>          ")
                    .concat("            <id id=\"68\" value=\"19c09a1e-d1ab-4a95-8051-f06debd348af\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"55\"/>                                             ")
                    .concat("            <borderColor reference=\"56\"/>                                                 ")
                    .concat("            <textColor reference=\"56\"/>                                                   ")
                    .concat("            <text id=\"69\" justification=\"0\" size=\"4\" underlined=\"false\">            ")
                    .concat("                <text>{                                                                     ")
                    .concat("                    &quot;comment&quot;: &quot;Will sum both results&quot;,                 ")
                    .concat("                    &quot;package&quot;: &quot;somossuinos.jackketch.transform.violet&quot;,")
                    .concat("                    &quot;class&quot;: &quot;SimpleDiagram&quot;,                           ")
                    .concat("                    &quot;method&quot;: &quot;sumXPlusY&quot;                               ")
                    .concat("                    }</text>                                                                ")
                    .concat("            </text>                                                                         ")
                    .concat("            <color reference=\"58\"/>                                                       ")
                    .concat("        </NoteNode>                                                                         ")
                    .concat("        <NoteNode id=\"70\">                                                                ")
                    .concat("            <children id=\"71\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"72\" x=\"270.0\" y=\"660.0\"/>          ")
                    .concat("            <id id=\"73\" value=\"7e9060b5-e651-48de-85ed-64909b4cc84e\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"55\"/>                                             ")
                    .concat("            <borderColor reference=\"56\"/>                                                 ")
                    .concat("            <textColor reference=\"56\"/>                                                   ")
                    .concat("            <text id=\"74\" justification=\"0\" size=\"4\" underlined=\"false\">            ")
                    .concat("                <text>{                                                                     ")
                    .concat("                    &quot;comment&quot;: &quot;Will save okay in the context&quot;,         ")
                    .concat("                    &quot;package&quot;: &quot;somossuinos.jackketch.transform.violet&quot;,")
                    .concat("                    &quot;class&quot;: &quot;SimpleDiagram&quot;,                           ")
                    .concat("                    &quot;method&quot;: &quot;showOk&quot;                                  ")
                    .concat("                    }</text>                                                                ")
                    .concat("            </text>                                                                         ")
                    .concat("            <color reference=\"58\"/>                                                       ")
                    .concat("        </NoteNode>                                                                         ")
                    .concat("        <NoteNode id=\"75\">                                                                ")
                    .concat("            <children id=\"76\"/>                                                           ")
                    .concat("            <location class=\"Point2D.Double\" id=\"77\" x=\"950.0\" y=\"660.0\"/>          ")
                    .concat("            <id id=\"78\" value=\"c6957c93-9ec3-4411-921c-83cd18cb853b\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <backgroundColor reference=\"55\"/>                                             ")
                    .concat("            <borderColor reference=\"56\"/>                                                 ")
                    .concat("            <textColor reference=\"56\"/>                                                   ")
                    .concat("            <text id=\"79\" justification=\"0\" size=\"4\" underlined=\"false\">            ")
                    .concat("                <text>{                                                                     ")
                    .concat("                    &quot;comment&quot;: &quot;Will save not okay in the context&quot;,     ")
                    .concat("                    &quot;package&quot;: &quot;somossuinos.jackketch.transform.violet&quot;,")
                    .concat("                    &quot;class&quot;: &quot;SimpleDiagram&quot;,                           ")
                    .concat("                    &quot;method&quot;: &quot;showNotOk&quot;                               ")
                    .concat("                    }</text>                                                                ")
                    .concat("            </text>                                                                         ")
                    .concat("            <color reference=\"58\"/>                                                       ")
                    .concat("        </NoteNode>                                                                         ")
                    .concat("    </nodes>                                                                                ")
                    .concat("    <edges id=\"80\">                                                                       ")
                    .concat("        <ActivityTransitionEdge id=\"81\">                                                  ")
                    .concat("            <start class=\"ScenarioStartNode\" reference=\"3\"/>                            ")
                    .concat("            <end class=\"SynchronizationBarNode\" reference=\"9\"/>                         ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"82\" x=\"10.0\" y=\"10.0\"/>       ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"83\" x=\"50.0\" y=\"0.0\"/>          ")
                    .concat("            <transitionPoints id=\"84\"/>                                                   ")
                    .concat("            <id id=\"85\" value=\"735cfe1e-4e6b-42c2-bb0b-74af16463361\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <lineStyle name=\"SOLID\"/>                                                     ")
                    .concat("            <startArrowHead name=\"NONE\"/>                                                 ")
                    .concat("            <bentStyle name=\"AUTO\"/>                                                      ")
                    .concat("            <startLabel></startLabel>                                                       ")
                    .concat("            <middleLabel></middleLabel>                                                     ")
                    .concat("            <endLabel></endLabel>                                                           ")
                    .concat("        </ActivityTransitionEdge>                                                           ")
                    .concat("        <ActivityTransitionEdge id=\"86\">                                                  ")
                    .concat("            <start class=\"SynchronizationBarNode\" reference=\"9\"/>                       ")
                    .concat("            <end class=\"ActivityNode\" reference=\"13\"/>                                  ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"87\" x=\"22.0\" y=\"0.0\"/>        ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"88\" x=\"40.0\" y=\"20.0\"/>         ")
                    .concat("            <transitionPoints id=\"89\"/>                                                   ")
                    .concat("            <id id=\"90\" value=\"f475eb75-9954-4ef7-ad14-76c4e8d762a0\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <lineStyle name=\"SOLID\"/>                                                     ")
                    .concat("            <startArrowHead name=\"NONE\"/>                                                 ")
                    .concat("            <bentStyle name=\"AUTO\"/>                                                      ")
                    .concat("            <startLabel></startLabel>                                                       ")
                    .concat("            <middleLabel></middleLabel>                                                     ")
                    .concat("            <endLabel></endLabel>                                                           ")
                    .concat("        </ActivityTransitionEdge>                                                           ")
                    .concat("        <ActivityTransitionEdge id=\"91\">                                                  ")
                    .concat("            <start class=\"SynchronizationBarNode\" reference=\"9\"/>                       ")
                    .concat("            <end class=\"ActivityNode\" reference=\"18\"/>                                  ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"92\" x=\"192.0\" y=\"0.0\"/>       ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"93\" x=\"60.0\" y=\"20.0\"/>         ")
                    .concat("            <transitionPoints id=\"94\"/>                                                   ")
                    .concat("            <id id=\"95\" value=\"14f6bc3b-a0ea-439c-b934-67ee80381d54\"/>                  ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <lineStyle name=\"SOLID\"/>                                                     ")
                    .concat("            <startArrowHead name=\"NONE\"/>                                                 ")
                    .concat("            <bentStyle name=\"AUTO\"/>                                                      ")
                    .concat("            <startLabel></startLabel>                                                       ")
                    .concat("            <middleLabel></middleLabel>                                                     ")
                    .concat("            <endLabel></endLabel>                                                           ")
                    .concat("        </ActivityTransitionEdge>                                                           ")
                    .concat("        <ActivityTransitionEdge id=\"96\">                                                  ")
                    .concat("            <start class=\"ActivityNode\" reference=\"13\"/>                                ")
                    .concat("            <end class=\"SynchronizationBarNode\" reference=\"23\"/>                        ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"97\" x=\"60.0\" y=\"40.0\"/>       ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"98\" x=\"60.0\" y=\"0.0\"/>          ")
                    .concat("            <transitionPoints id=\"99\"/>                                                   ")
                    .concat("            <id id=\"100\" value=\"aa210d30-05ca-4198-93fd-b32e751a9f6a\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <lineStyle name=\"SOLID\"/>                                                     ")
                    .concat("            <startArrowHead name=\"NONE\"/>                                                 ")
                    .concat("            <bentStyle name=\"AUTO\"/>                                                      ")
                    .concat("            <startLabel></startLabel>                                                       ")
                    .concat("            <middleLabel></middleLabel>                                                     ")
                    .concat("            <endLabel></endLabel>                                                           ")
                    .concat("        </ActivityTransitionEdge>                                                           ")
                    .concat("        <ActivityTransitionEdge id=\"101\">                                                 ")
                    .concat("            <start class=\"ActivityNode\" reference=\"18\"/>                                ")
                    .concat("            <end class=\"SynchronizationBarNode\" reference=\"23\"/>                        ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"102\" x=\"40.0\" y=\"40.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"103\" x=\"52.0\" y=\"0.0\"/>         ")
                    .concat("            <transitionPoints id=\"104\"/>                                                  ")
                    .concat("            <id id=\"105\" value=\"98daa777-7cd0-4473-ba71-7a97de25d5e3\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <lineStyle name=\"SOLID\"/>                                                     ")
                    .concat("            <startArrowHead name=\"NONE\"/>                                                 ")
                    .concat("            <bentStyle name=\"AUTO\"/>                                                      ")
                    .concat("            <startLabel></startLabel>                                                       ")
                    .concat("            <middleLabel></middleLabel>                                                     ")
                    .concat("            <endLabel></endLabel>                                                           ")
                    .concat("        </ActivityTransitionEdge>                                                           ")
                    .concat("        <ActivityTransitionEdge id=\"106\">                                                 ")
                    .concat("            <start class=\"SynchronizationBarNode\" reference=\"23\"/>                      ")
                    .concat("            <end class=\"ActivityNode\" reference=\"27\"/>                                  ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"107\" x=\"202.0\" y=\"0.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"108\" x=\"40.0\" y=\"30.0\"/>        ")
                    .concat("            <transitionPoints id=\"109\"/>                                                  ")
                    .concat("            <id id=\"110\" value=\"fa76b600-fb83-47cc-b10c-df4d7bca69d2\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <lineStyle name=\"SOLID\"/>                                                     ")
                    .concat("            <startArrowHead name=\"NONE\"/>                                                 ")
                    .concat("            <bentStyle name=\"AUTO\"/>                                                      ")
                    .concat("            <startLabel></startLabel>                                                       ")
                    .concat("            <middleLabel></middleLabel>                                                     ")
                    .concat("            <endLabel></endLabel>                                                           ")
                    .concat("        </ActivityTransitionEdge>                                                           ")
                    .concat("        <ActivityTransitionEdge id=\"111\">                                                 ")
                    .concat("            <start class=\"ActivityNode\" reference=\"27\"/>                                ")
                    .concat("            <end class=\"DecisionNode\" reference=\"32\"/>                                  ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"112\" x=\"30.0\" y=\"30.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"113\" x=\"40.0\" y=\"10.0\"/>        ")
                    .concat("            <transitionPoints id=\"114\"/>                                                  ")
                    .concat("            <id id=\"115\" value=\"a59c585e-6c65-493a-ac69-dad104f8db2b\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <lineStyle name=\"SOLID\"/>                                                     ")
                    .concat("            <startArrowHead name=\"NONE\"/>                                                 ")
                    .concat("            <bentStyle name=\"AUTO\"/>                                                      ")
                    .concat("            <startLabel></startLabel>                                                       ")
                    .concat("            <middleLabel></middleLabel>                                                     ")
                    .concat("            <endLabel></endLabel>                                                           ")
                    .concat("        </ActivityTransitionEdge>                                                           ")
                    .concat("        <ActivityTransitionEdge id=\"116\">                                                 ")
                    .concat("            <start class=\"DecisionNode\" reference=\"32\"/>                                ")
                    .concat("            <end class=\"ActivityNode\" reference=\"37\"/>                                  ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"117\" x=\"30.0\" y=\"20.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"118\" x=\"30.0\" y=\"40.0\"/>        ")
                    .concat("            <transitionPoints id=\"119\"/>                                                  ")
                    .concat("            <id id=\"120\" value=\"0c3e9b5b-9234-4927-a5b8-f910ac55d710\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <lineStyle name=\"SOLID\"/>                                                     ")
                    .concat("            <startArrowHead name=\"NONE\"/>                                                 ")
                    .concat("            <bentStyle name=\"HV\"/>                                                        ")
                    .concat("            <startLabel></startLabel>                                                       ")
                    .concat("            <middleLabel>v LEQT 6</middleLabel>                                            ")
                    .concat("            <endLabel></endLabel>                                                           ")
                    .concat("        </ActivityTransitionEdge>                                                           ")
                    .concat("        <ActivityTransitionEdge id=\"121\">                                                 ")
                    .concat("            <start class=\"DecisionNode\" reference=\"32\"/>                                ")
                    .concat("            <end class=\"ActivityNode\" reference=\"42\"/>                                  ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"122\" x=\"40.0\" y=\"20.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"123\" x=\"50.0\" y=\"30.0\"/>        ")
                    .concat("            <transitionPoints id=\"124\"/>                                                  ")
                    .concat("            <id id=\"125\" value=\"0e97cd98-8e17-4ed3-ba6d-89edb313765c\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <lineStyle name=\"SOLID\"/>                                                     ")
                    .concat("            <startArrowHead name=\"NONE\"/>                                                 ")
                    .concat("            <bentStyle name=\"HV\"/>                                                        ")
                    .concat("            <startLabel></startLabel>                                                       ")
                    .concat("            <middleLabel>otherwise</middleLabel>                                            ")
                    .concat("            <endLabel></endLabel>                                                           ")
                    .concat("        </ActivityTransitionEdge>                                                           ")
                    .concat("        <ActivityTransitionEdge id=\"126\">                                                 ")
                    .concat("            <start class=\"ActivityNode\" reference=\"37\"/>                                ")
                    .concat("            <end class=\"ScenarioEndNode\" reference=\"47\"/>                               ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"127\" x=\"50.0\" y=\"50.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"128\" x=\"10.0\" y=\"10.0\"/>        ")
                    .concat("            <transitionPoints id=\"129\"/>                                                  ")
                    .concat("            <id id=\"130\" value=\"b8e2ecd0-3d51-48b8-aebb-41b0c9c4b909\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <lineStyle name=\"SOLID\"/>                                                     ")
                    .concat("            <startArrowHead name=\"NONE\"/>                                                 ")
                    .concat("            <bentStyle name=\"AUTO\"/>                                                      ")
                    .concat("            <startLabel></startLabel>                                                       ")
                    .concat("            <middleLabel></middleLabel>                                                     ")
                    .concat("            <endLabel></endLabel>                                                           ")
                    .concat("        </ActivityTransitionEdge>                                                           ")
                    .concat("        <ActivityTransitionEdge id=\"131\">                                                 ")
                    .concat("            <start class=\"ActivityNode\" reference=\"42\"/>                                ")
                    .concat("            <end class=\"ScenarioEndNode\" reference=\"47\"/>                               ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"132\" x=\"20.0\" y=\"40.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"133\" x=\"10.0\" y=\"10.0\"/>        ")
                    .concat("            <transitionPoints id=\"134\"/>                                                  ")
                    .concat("            <id id=\"135\" value=\"5d666f63-65aa-4a8b-a1c8-f5fcd7e18657\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("            <lineStyle name=\"SOLID\"/>                                                     ")
                    .concat("            <startArrowHead name=\"NONE\"/>                                                 ")
                    .concat("            <bentStyle name=\"AUTO\"/>                                                      ")
                    .concat("            <startLabel></startLabel>                                                       ")
                    .concat("            <middleLabel></middleLabel>                                                     ")
                    .concat("            <endLabel></endLabel>                                                           ")
                    .concat("        </ActivityTransitionEdge>                                                           ")
                    .concat("        <NoteEdge id=\"136\">                                                               ")
                    .concat("            <start class=\"NoteNode\" reference=\"51\"/>                                    ")
                    .concat("            <end class=\"ActivityNode\" reference=\"18\"/>                                  ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"137\" x=\"10.0\" y=\"20.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"138\" x=\"50.0\" y=\"30.0\"/>        ")
                    .concat("            <transitionPoints id=\"139\"/>                                                  ")
                    .concat("            <id id=\"140\" value=\"1b1f97c5-5092-41a1-8fc5-3039cbea55c8\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("        </NoteEdge>                                                                         ")
                    .concat("        <NoteEdge id=\"141\">                                                               ")
                    .concat("            <start class=\"NoteNode\" reference=\"59\"/>                                    ")
                    .concat("            <end class=\"ActivityNode\" reference=\"13\"/>                                  ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"142\" x=\"40.0\" y=\"20.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"143\" x=\"30.0\" y=\"30.0\"/>        ")
                    .concat("            <transitionPoints id=\"144\"/>                                                  ")
                    .concat("            <id id=\"145\" value=\"de6ff169-91e2-4a7d-abba-f87478bfb416\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("        </NoteEdge>                                                                         ")
                    .concat("        <NoteEdge id=\"146\">                                                               ")
                    .concat("            <start class=\"NoteNode\" reference=\"65\"/>                                    ")
                    .concat("            <end class=\"ActivityNode\" reference=\"27\"/>                                  ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"147\" x=\"30.0\" y=\"20.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"148\" x=\"50.0\" y=\"30.0\"/>        ")
                    .concat("            <transitionPoints id=\"149\"/>                                                  ")
                    .concat("            <id id=\"150\" value=\"93c5fae6-6b24-4a7c-8d66-79d304010cf8\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("        </NoteEdge>                                                                         ")
                    .concat("        <NoteEdge id=\"151\">                                                               ")
                    .concat("            <start class=\"NoteNode\" reference=\"70\"/>                                    ")
                    .concat("            <end class=\"ActivityNode\" reference=\"37\"/>                                  ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"152\" x=\"40.0\" y=\"20.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"153\" x=\"40.0\" y=\"30.0\"/>        ")
                    .concat("            <transitionPoints id=\"154\"/>                                                  ")
                    .concat("            <id id=\"155\" value=\"c840562f-2530-449a-b285-814c71e4152d\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("        </NoteEdge>                                                                         ")
                    .concat("        <NoteEdge id=\"156\">                                                               ")
                    .concat("            <start class=\"NoteNode\" reference=\"75\"/>                                    ")
                    .concat("            <end class=\"ActivityNode\" reference=\"42\"/>                                  ")
                    .concat("            <startLocation class=\"Point2D.Double\" id=\"157\" x=\"20.0\" y=\"20.0\"/>      ")
                    .concat("            <endLocation class=\"Point2D.Double\" id=\"158\" x=\"50.0\" y=\"20.0\"/>        ")
                    .concat("            <transitionPoints id=\"159\"/>                                                  ")
                    .concat("            <id id=\"160\" value=\"5478ad41-3a98-43a5-b97b-23fa8cabab92\"/>                 ")
                    .concat("            <revision>1</revision>                                                          ")
                    .concat("        </NoteEdge>                                                                         ")
                    .concat("    </edges>                                                                                ")
                    .concat("</ActivityDiagramGraph>                                                                     ");

    public static String getXml() {
        return XML;
    }
}
